feeds:
  - name: "DaringFireball"
    url: "https://daringfireball.net/feeds/main"
  - name: "pgessays"
    url: "http://www.aaronsw.com/2002/feeds/pgessays.rss"
  - name: "SimonWillison"
    url: "https://simonwillison.net/atom/everything/"
  # 按这个格式添加更多源
