feeds:
  - name: "DaringFireball"
    url: "https://daringfireball.net/feeds/main"
  - name: "pgessays"
    url: "http://www.aaronsw.com/2002/feeds/pgessays.rss"
  - name: "SimonWillison"
    url: "https://simonwillison.net/atom/everything/"
  - name: "marco"
    url: "https://marco.org/rss"
  - name: "dereksivers"
    url: "https://sive.rs/en.atom"
  - name: "kaushikgopal"
    url: "https://kau.sh/feed.xml"
  - name: "astralcodexten"
    url: "https://www.astralcodexten.com/feed"
  - name: "thinkingoutloud"
    url: "https://newsletter.jantegze.com/feed"
  - name: "AnthropicNews"
    url: "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_anthropic_news.xml"
  # 按这个格式添加更多源
